services:
  jupyter-server:
    build:
      context: ./workspace
      dockerfile: Dockerfile
    container_name: jupyter-server
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - LOCAL_GROUP_ID=${LOCAL_GROUP_ID}
    command:
      - jupyter
      # - lab
      - server
      - --ip=0.0.0.0
      - --port=8888
      - --no-browser
      - --allow-root
      - --NotebookApp.token=''
      - --NotebookApp.password=''
      - --ServerApp.disable_check_xsrf=True
      - --notebook-dir=/workspace
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:5000"
    volumes:
      - ./backend:/backend
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - LOCAL_GROUP_ID=${LOCAL_GROUP_ID}
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: bash -c "sleep infinity"
    # command: bash -c "flask run"